{% set name = "optlang" %}
{% set version = "1.7.0" %}
{% set sha256 = "04e4b5e838a6063eb03ae2f2ae82b7aed10e1031aea0a07017dc75ad81c7d243" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - sympy >=1.12
    - six >=1.9
    - swiglpk >=5.0
    - symengine >=0.6.0

test:
  imports:
    - optlang
    - optlang.tests
    - optlang.tests.data

about:
  home: https://github.com/biosustain/optlang
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: optlang - sympy based mathematical programming language

  description: |
    Optlang is a Python package for solving mathematical optimization problems,
    i.e. maximizing or minimizing an objective function over a set of variables
    subject to a number of constraints.  Optlang provides a common interface to
    a series of optimization tools, so different solver backends can be changed
    in a transparent way.
  doc_url: http://optlang.readthedocs.io/
  dev_url: https://github.com/biosustain/optlang

extra:
  recipe-maintainers:
    - druvus
    - Midnighter
    - phantomas1234
